// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yuxkrdvcrnawswkofulw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1eGtyZHZjcm5hd3N3a29mdWx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ2MTA4MzgsImV4cCI6MjA1MDE4NjgzOH0.4ZMMsaj6H5_Pxjvpg87bMBt8aepPa8TJd48ug9H17wM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);